working_directory: /usr/src/app
proxy_file_name: /usr/src/app/cadcproxy.pem
state_file_name: state.yml
# operational value is ivo://cadc.nrc.ca/ams
# resource_id: ivo://cadc.nrc.ca/sc2repo
resource_id: ivo://cadc.nrc.ca/ams
tap_id: ivo://cadc.nrc.ca/ams/gemini
todo_file_name: todo.txt
# values True False
use_local_files: False
# values DEBUG INFO WARNING ERROR
logging_level: INFO
# values True False
log_to_file: True
# fully qualified name for a directory to write log files
log_file_directory: /usr/src/app/logs
# the filename where success logs are written
#
# this file is created in the logs directory, default is 'success_log.txt'
success_log_file_name: success_log.txt
# the filename where failure logs are written
#
# this file is created in the logs directory, default is 'failure_log.txt'
failure_log_file_name: failure_log.txt
# the filename where retry ids are written. This file is only written
# if use_local_files is False.
#
# this file is created in the logs directory, default is 'retries.txt'
retry_file_name: retries.txt
retry_failures: False
# ad stream value - sorry
stream: default
collection: GEMINI
archive: GEM
schema: gemini
# how many minutes the run_query timestamp chunk is going to process
interval: 1440
observe_execution: True
observable_directory: /usr/src/app/metrics
rejected_file_name: rejected.yml
rejected_directory: /usr/src/app/rejected
# how to control the work that gets done
# possible values are:
# - scrape, store, ingest, modify, visit
task_types: 
  - visit
features:
  use_file_names: False
  use_urls: False
